### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by rarkins** [nice-registry/nice-registry#4]
The package URL for this on npmjs (https://www.npmjs.com/package/nice-registry) points to the wrong location, which now 404s. I think if you publish a bumped 1.1.4 then it should fix it.

![image](https://user-images.githubusercontent.com/6311784/34107330-2473a2f6-e3fc-11e7-898f-0066a7954a82.png)

**Comment by zeke** [comment]
Thanks for noticing, @rarkins.

```
$ np minor --yolo
 ✔ Prerequisite check
 ✔ Git
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 nice-registry 1.3.0 published 🎉
```

Note that this project is experimental and probably doesn't really work right now. I hope to dust it off at some point and make it real.
